/* ==========================================================================
   Kandy's Treats — Basket page
   Shares its line and summary renderers with the drawer so the two can never
   drift. Fulfilment, coupon and address choices here become the checkout
   draft that `createCheckoutOrder` validates server-side.
   ========================================================================== */
(function (KT) {
  "use strict";

  KT.pages = KT.pages || {};

  var addresses = [];
  var selectedAddressId = "";
  /* False until the menu (live, cached or the offline snapshot) or the
     services have answered once. Until then a stored basket cannot be priced
     or named, but it is not empty either. */
  var menuHeard = false;

  /* Pack labels are generated by the store and line keys are menu uuids, so
     neither is attacker-controlled today. Escaped anyway: these values reach
     an attribute, and a renderer that only works because of what its callers
     happen to pass is one refactor from being wrong. */
  function esc(v) {
    return String(v == null ? "" : v)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;")
      .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }

  /* ---- Basket ---------------------------------------------------------- */

  /* The shape of the basket while its dishes load: the same header and one
     line-sized row per stored line, so the real basket lands in place rather
     than replacing a flash of "Your basket is empty". */
  function pendingHTML(stored) {
    var rows = "";
    for (var i = 0; i < Math.min(stored.length || 2, 8); i++) {
      rows +=
        '<li class="cline sk-cline">' +
          '<span class="cline__media ring skeleton"></span>' +
          '<div class="cline__body">' +
            '<div class="cline__top">' + KT.skeleton.box("58%", "18px", "6px") +
              KT.skeleton.box("64px", "18px", "6px") + "</div>" +
            '<p class="cline__extras">' + KT.skeleton.box("34%", "12px", "6px") + "</p>" +
            '<div class="cline__controls">' + KT.skeleton.box("114px", "42px", "var(--r-pill)") + "</div>" +
          "</div>" +
        "</li>";
    }
    return '<div class="sk-hold">' + KT.loadingLabel("Loading your basket…") +
      '<div class="cartpage__head" aria-hidden="true"><h2>' +
        (stored.length ? KT.plural(KT.cart.count(), "item") + " in your basket"
                       : KT.skeleton.box("46%", "20px", "6px")) + "</h2></div>" +
      '<ul class="clines" aria-hidden="true">' + rows + "</ul></div>";
  }

  function renderMain() {
    var lines = KT.cart.detailed();
    var host = KT.qs("[data-cart-main]");
    if (!host) return;

    if (!lines.length) {
      var stored = KT.cart.lines();
      /* Two ways a basket that is not empty can look empty for a moment:
         its dishes are not loaded yet, or a returning customer's session is
         still restoring and the store is still on the guest basket. */
      var waiting = (stored.length && !KT.menu.live && !menuHeard) || KT.authResolving();
      host.innerHTML = waiting ? pendingHTML(stored) : KT.components.cartEmpty();
      return;
    }

    host.innerHTML =
      '<div class="cartpage__head">' +
        "<h2>" + KT.plural(KT.cart.count(), "item") + " in your basket</h2>" +
        '<button class="cline__remove" type="button" data-clear-cart>' +
          KT.icon("trash", 15) + "<span>Empty basket</span></button>" +
      "</div>" +
      KT.components.cartProgress(KT.cart.summary()) +
      takeawayHTML() +
      basketHTML(lines);

    KT.images.bindAll(host);
  }

  /* ---- Takeaway packs -------------------------------------------------- */

  /*
     GROUPING IS FREE, IN BOTH SENSES. Splitting a basket into packs tells the
     kitchen which items go in which bag; it does not change the subtotal, the
     packaging charge, delivery, the coupon or the total. Packaging is still
     one charge for the whole order — the server computes it from the food in
     the basket and ignores packs entirely — so the strip below says so
     outright rather than leaving the customer to wonder what a second bag
     costs.

     Off by default. A customer who never touches it gets the flat basket that
     has always been here.
  */
  function takeawayHTML() {
    var groups = KT.cart.groupCount();
    var atMax = groups >= KT.cart.maxGroups();

    if (!groups) {
      return (
        '<div class="takeaway takeaway--off">' +
          '<div class="takeaway__intro">' +
            '<span class="takeaway__icon">' + KT.icon("cart", 18) + "</span>" +
            "<div><strong>Splitting this between people?</strong>" +
            "<p>Group items into separate takeaway packs so the kitchen bags " +
            "them apart. Packaging stays the same price.</p></div>" +
          "</div>" +
          '<button class="btn btn--soft btn--sm" type="button" data-takeaway-add>' +
            KT.icon("plus", 15) + "<span>Split into packs</span></button>" +
        "</div>"
      );
    }

    var active = KT.cart.activeGroup();
    var tabs = "";
    for (var g = 1; g <= groups; g += 1) {
      tabs +=
        '<button class="takeaway__tab' + (g === active ? " is-active" : "") + '" ' +
          'type="button" data-takeaway-pick="' + g + '" ' +
          'aria-pressed="' + (g === active ? "true" : "false") + '">' +
          "Takeaway " + g +
        "</button>";
    }

    return (
      '<div class="takeaway">' +
        '<div class="takeaway__head">' +
          "<strong>Takeaway packs</strong>" +
          '<span class="takeaway__note">Packaging is charged once for the ' +
            "whole order, however many packs you use.</span>" +
        "</div>" +
        '<div class="takeaway__tabs" role="group" aria-label="Choose the pack new items go into">' +
          tabs +
          (atMax ? "" :
            '<button class="takeaway__tab takeaway__tab--add" type="button" ' +
              'data-takeaway-add aria-label="Add another takeaway pack">' +
              KT.icon("plus", 15) + "</button>") +
        "</div>" +
        '<p class="takeaway__hint">New items go into <strong>Takeaway ' +
          active + "</strong>.</p>" +
      "</div>"
    );
  }

  /* Grouped baskets render pack by pack, each with its own heading, count and
     a control to drop that pack. An ungrouped basket renders exactly the flat
     <ul class="clines"> it always did. */
  function basketHTML(lines) {
    if (!KT.cart.grouped()) {
      return '<ul class="clines">' +
        lines.map(function (l) { return KT.components.cartLine(l); }).join("") +
      "</ul>";
    }

    return KT.cart.byGroup().map(function (bucket) {
      var count = bucket.lines.reduce(function (n, l) { return n + l.qty; }, 0);
      return (
        '<section class="cpack' +
          (bucket.group === KT.cart.activeGroup() ? " is-active" : "") + '">' +
          '<header class="cpack__head">' +
            "<h3>" + esc(bucket.label) + "</h3>" +
            '<span class="cpack__count">' + KT.plural(count, "item") + "</span>" +
            (bucket.group == null ? "" :
              '<button class="cpack__drop" type="button" data-takeaway-drop="' +
                bucket.group + '" aria-label="Remove ' + esc(bucket.label) + '">' +
                KT.icon("trash", 15) + "</button>") +
          "</header>" +
          (bucket.lines.length
            ? '<ul class="clines">' +
                bucket.lines.map(function (l) {
                  return KT.components.cartLine(l) + moveHTML(l);
                }).join("") +
              "</ul>"
            : '<p class="cpack__empty">Nothing in this pack yet — select it ' +
              "above, then add from the menu.</p>") +
        "</section>"
      );
    }).join("");
  }

  /* Moving a line between packs. Rendered as a row of destination chips
     rather than a <select>, because on a phone a native select is a modal
     and this is a one-tap decision. */
  function moveHTML(l) {
    var groups = KT.cart.groupCount();
    if (groups < 2) return "";
    var chips = "";
    for (var g = 1; g <= groups; g += 1) {
      if (g === l.group) continue;
      chips += '<button class="cmove__chip" type="button" ' +
        'data-takeaway-move="' + esc(l.key) + '" data-takeaway-to="' + g + '">' +
        g + "</button>";
    }
    if (!chips) return "";
    return '<li class="cmove"><span class="cmove__label">Move to</span>' +
      chips + "</li>";
  }

  /*
     The last thing a customer reads before paying. Only rendered for a
     grouped basket — an ungrouped order sees the summary panel exactly as it
     was. No prices per pack, deliberately: packaging is one order-level
     charge and printing a money column beside each pack would imply
     otherwise.
  */
  function packRecapHTML() {
    if (!KT.cart.grouped()) return "";
    var buckets = KT.cart.byGroup().filter(function (b) { return b.lines.length; });
    if (!buckets.length) return "";

    return (
      '<div class="precap">' +
        '<p class="precap__head">Going out in ' +
          KT.plural(buckets.length, "pack") + "</p>" +
        buckets.map(function (b) {
          return '<div class="precap__pack">' +
            '<strong class="precap__name">' + esc(b.label) + "</strong>" +
            "<ul>" + b.lines.map(function (l) {
              return "<li>" + esc(l.item.name) +
                ' <span class="precap__qty">×' + l.qty + "</span></li>";
            }).join("") + "</ul>" +
          "</div>";
        }).join("") +
      "</div>"
    );
  }

  /* ---- Fulfilment + address ------------------------------------------- */

  function addressPicker() {
    if (KT.cart.fulfilment() === "pickup") {
      return (
        '<div class="deliverycard">' +
          '<span class="deliverycard__icon">' + KT.icon("pin", 19) + "</span>" +
          "<div><strong>Collect from Kandy's</strong>" +
          "<p>Pick your order up yourself — no delivery fee. We will call when it is ready.</p></div>" +
        "</div>"
      );
    }

    if (KT.authResolving()) {
      return '<div class="deliverycard sk-panel" aria-hidden="true">' +
        KT.skeleton.box("38px", "38px", "50%") +
        '<span class="sk-lines">' + KT.skeleton.box("60%", "13px", "6px") +
        KT.skeleton.box("85%", "11px", "6px") + "</span></div>" +
        KT.loadingLabel("Loading your saved addresses…");
    }

    /* Say nothing until the session is known — otherwise a signed-in customer
       sees "Sign in to add an address" for a moment on every cart load. */
    if (KT.authResolving && KT.authResolving()) {
      return '<div class="deliverycard"><span class="deliverycard__icon">' +
        KT.spinner(18) + "</span><div><strong>Checking your account…</strong>" +
        "<p>One moment while we load your saved addresses.</p></div></div>";
    }

    if (!KT.auth || !KT.auth.user()) {
      return (
        '<div class="deliverycard">' +
          '<span class="deliverycard__icon">' + KT.icon("lock", 19) + "</span>" +
          "<div><strong>Sign in to add an address</strong>" +
          "<p>Delivery addresses are saved to your account so the rider always has the right one.</p>" +
          '<a class="deliverycard__change" href="' + KT.url("pages/login.html?next=cart") +
            '">Sign in or create an account</a></div>' +
        "</div>"
      );
    }

    if (!addresses.length) {
      return (
        '<div class="deliverycard">' +
          '<span class="deliverycard__icon">' + KT.icon("pin", 19) + "</span>" +
          "<div><strong>No saved address yet</strong>" +
          "<p>" + KT.config.serviceArea.note + "</p>" +
          '<a class="deliverycard__change" href="' + KT.url("pages/account.html#addresses") +
            '">Add a delivery address</a></div>' +
        "</div>"
      );
    }

    return addresses.map(function (a) {
      var on = a.id === selectedAddressId;
      return (
        '<button class="deliverycard" type="button" data-pick-address="' + a.id + '"' +
          (on ? ' style="border-color:var(--kt-pink);background:var(--kt-pink-50)"' : "") + ">" +
          '<span class="deliverycard__icon">' + KT.icon(on ? "check" : "pin", 19) + "</span>" +
          "<div><strong>" + a.label + (a.isDefault ? " · Default" : "") + "</strong>" +
          "<p>" + a.address + "</p>" +
          (a.recipientName || a.phone
            ? "<small>" + [a.recipientName, KT.rules.displayPhone(a.phone)].filter(Boolean).join(" · ") + "</small>"
            : "") +
          "</div>" +
        "</button>"
      );
    }).join("") +
      '<a class="deliverycard__change" href="' + KT.url("pages/account.html#addresses") +
      '">Manage addresses</a>';
  }

  function renderSide() {
    var sum = KT.cart.summary();
    var host = KT.qs("[data-cart-side]");
    if (!host) return;
    var empty = sum.count === 0;
    var needsAddress = sum.fulfilment === "delivery" && !selectedAddressId;
    var signedIn = !!(KT.auth && KT.auth.user());
    var authPending = KT.authResolving();

    host.innerHTML =
      '<div class="cartpanel">' +
        "<h3>How would you like it?</h3>" +
        '<div class="slotpicker" role="group" aria-label="Fulfilment">' +
          KT.rules.FULFILMENTS.map(function (f) {
            var on = sum.fulfilment === f;
            return '<button class="chip' + (on ? " is-active" : "") + '" type="button" ' +
              'data-fulfilment="' + f + '" aria-pressed="' + on + '">' +
              KT.icon(f === "delivery" ? "bike" : "pin", 15) +
              (f === "delivery" ? "Deliver to me" : "I'll pick it up") + "</button>";
          }).join("") +
        "</div>" +
        '<div class="slotpicker" style="flex-direction:column;align-items:stretch;gap:8px">' +
          addressPicker() + "</div>" +
        (sum.eta ? KT.components.cartEta(sum) : "") +
      "</div>" +

      '<div class="cartpanel">' +
        "<h3>Order summary</h3>" +
        packRecapHTML() +
        '<form class="promoform" data-promo-form>' +
          '<label class="sr-only" for="promoCode">Promo code</label>' +
          '<input class="input" id="promoCode" placeholder="Promo code" autocomplete="off" value="' +
            (sum.couponCode || "") + '">' +
          '<button class="btn btn--ghost" type="submit">' +
            (sum.couponCode ? "Remove" : "Apply") + "</button>" +
        "</form>" +
        '<p class="field__hint" data-promo-msg></p>' +
        KT.components.cartSummary(sum) +
        '<button class="btn btn--primary btn--lg btn--block" type="button" data-checkout' +
          (empty || sum.hasSoldOut || authPending ? " disabled" : "") + ">" +
          (authPending
            ? KT.spinner(17) + "<span>Just a moment…</span>"
            : (signedIn ? "Continue to payment" : "Sign in to check out") +
              KT.icon("arrowRight", 18)) + "</button>" +
        (needsAddress && !empty && signedIn
          ? '<p class="field__hint" style="color:var(--chili)">Choose a delivery address first.</p>'
          : "") +
        (sum.hasSoldOut
          ? '<p class="field__hint" style="color:var(--chili)">Remove the sold-out items to continue.</p>'
          : "") +
        '<div class="phasenote">' + KT.icon("lock", 16) +
          "<span>Totals are recalculated on our server before payment. Card details never touch this site — " +
          "Paystack and Flutterwave handle them.</span></div>" +
      "</div>";
  }

  function suggestions() {
    var host = KT.qs("[data-cart-suggest]");
    if (!host) return;
    var inBasket = KT.cart.lines().map(function (l) { return l.menuId; });
    var picks = KT.menu.byCategory("drinks")
      .concat(KT.menu.byCategory("sides"))
      .filter(function (i) { return inBasket.indexOf(i.id) === -1 && KT.menu.available(i); })
      .slice(0, 4);
    host.innerHTML = KT.components.foodCards(picks);
    KT.images.bindAll(host);
    KT.components.paintCards(host);
  }

  function paint() {
    renderMain();
    renderSide();
    suggestions();
  }

  /* ---- Data ------------------------------------------------------------ */

  function loadAddresses() {
    if (!KT.services || !KT.auth || !KT.auth.user()) return;
    KT.services.addresses.list().then(function (list) {
      addresses = list || [];
      var preferred = addresses.filter(function (a) { return a.isDefault; })[0] || addresses[0];
      if (!selectedAddressId && preferred) selectedAddressId = preferred.id;
      renderSide();
    }).catch(function () { /* offline — the picker shows the signed-out state */ });
  }

  async function checkout() {
    if (!KT.services) {
      KT.toast("Still connecting to Kandy's — try again in a moment.", "info");
      return;
    }
    var user = KT.auth && KT.auth.user();
    if (!user) {
      window.location.href = KT.url("pages/login.html?next=cart");
      return;
    }
    if (!KT.menu.live) {
      KT.toast("We could not confirm today's menu. Refresh and try again.", "error");
      return;
    }

    var sum = KT.cart.summary();
    if (sum.fulfilment === "delivery" && !selectedAddressId) {
      KT.toast("Choose a delivery address first.", "info");
      return;
    }

    var done = KT.busy(KT.qs("[data-checkout]"), "Creating your order…");
    if (!done) return;

    try {
      var profile = await KT.services.account.profile();
      var address = addresses.filter(function (a) { return a.id === selectedAddressId; })[0];

      /* Pickup has no address, so the profile phone is the only way the
         kitchen can reach the customer ("we will call when it is ready").
         Accounts created with Google have none, so ask for it here — through
         the existing profile form — rather than sending an unreachable order. */
      if (sum.fulfilment === "pickup" && !KT.rules.isValidPhone(profile && profile.phone)) {
        done();
        pickupPhoneNeeded();
        return;
      }
      var draft = KT.cart.toDraft(selectedAddressId, {
        name: (profile && profile.displayName) || (address && address.recipientName) || user.displayName || "",
        phone: (profile && profile.phone) || (address && address.phone) || "",
        email: user.email || ""
      });

      var order = await KT.services.orders.createCheckout([draft], "gateway");
      /* Leaving for the order page — the button stays busy on purpose. */
      window.location.href = KT.url("pages/order-detail.html?id=" + encodeURIComponent(order.orderId) + "&pay=1");
    } catch (error) {
      done();
      /* Ordering paused from admin Settings. The database raises it with its
         own sentence (enforce_ordering_enabled); the old Firebase code
         "kt/ordering-unavailable" is kept only in case anything still sends it. */
      if (error && (error.code === "kt/ordering-unavailable" ||
          /ordering is paused/i.test(String(error.message || "")))) {
        orderingUnavailable(KT.services.errorMessage(error));
        return;
      }
      KT.toast(KT.services.errorMessage(error), "error", { duration: 5200 });
    }
  }

  /** Pickup without a usable phone: explain, and link to the profile form. */
  function pickupPhoneNeeded() {
    var message = "Add your phone number so we can call you when your pickup order is ready.";
    var target = KT.url("pages/account.html?section=profile&next=cart");
    /* The toast carries the action too: on a small screen it sits over the
       inline note for a few seconds, so whichever one is visible is tappable. */
    KT.toast(message, "info", {
      duration: 7000,
      action: "Add phone",
      onAction: function () { window.location.href = target; }
    });

    var btn = KT.qs("[data-checkout]");
    if (!btn || KT.qs("[data-pickup-phone-note]")) return;
    var note = KT.el("div.phasenote", {
      "data-pickup-phone-note": true,
      html: KT.icon("phone", 16) + "<span>" + message + ' <a href="' + target +
        '">Add a phone number</a>.</span>'
    });
    note.style.marginTop = "12px";
    btn.parentNode.insertBefore(note, btn.nextSibling);
  }

  /**
   * Online ordering needs createCheckoutOrder, a Cloud Function that is not
   * deployed. Say so plainly and leave the explanation on screen next to the
   * button rather than in a toast that scrolls away — the basket is not lost,
   * and the customer needs a way to actually order.
   */
  function orderingUnavailable(message) {
    KT.toast(message, "info", { duration: 7000 });

    var btn = KT.qs("[data-checkout]");
    if (!btn || KT.qs("[data-ordering-note]")) return;

    var b = KT.config.business || {};
    var contact = "";
    if (b.whatsapp) {
      contact = ' <a href="https://wa.me/' + b.whatsapp.replace(/[^0-9]/g, "") +
        '" target="_blank" rel="noopener noreferrer">Message us on WhatsApp</a>.';
    } else if (b.phone) {
      contact = ' <a href="tel:' + b.phone.replace(/[^+0-9]/g, "") + '">Call ' +
        b.phone + "</a>.";
    }

    var note = KT.el("div.phasenote", {
      "data-ordering-note": true,
      html: KT.icon("clock", 16) + "<span>" + message + contact + "</span>"
    });
    note.style.marginTop = "12px";
    btn.parentNode.insertBefore(note, btn.nextSibling);
  }

  /* ---- Wiring ---------------------------------------------------------- */

  KT.pages.cart = function () {
    paint();
    KT.cart.subscribe(KT.debounce(paint, 40));
    document.addEventListener("kt:auth", function () {
      selectedAddressId = "";
      addresses = [];
      loadAddresses();
      renderMain();
      renderSide();
    });
    document.addEventListener("kt:menu", function () { menuHeard = true; paint(); });
    /* renderSide() alone repainted the picker without ever fetching the
       addresses, so if kt:auth had already fired before this module
       registered its listener, selectedAddressId stayed empty and checkout
       refused with "Choose a delivery address first" despite a saved default.
       loadAddresses() calls renderSide() itself once the list arrives. */
    document.addEventListener("kt:services", /** @param {CustomEvent} e */ function (e) {
      /* Services down: no menu is coming, so stop holding the basket's shape. */
      if (!(e.detail && e.detail.ok) && !menuHeard) { menuHeard = true; paint(); }
      loadAddresses();
      renderSide();
    });
    loadAddresses();

    document.addEventListener("click", function (e) {
      var f = e.target.closest("[data-fulfilment]");
      if (f) KT.cart.setFulfilment(f.getAttribute("data-fulfilment"));

      var a = e.target.closest("[data-pick-address]");
      if (a) {
        selectedAddressId = a.getAttribute("data-pick-address");
        renderSide();
      }

      if (e.target.closest("[data-checkout]")) checkout();

      /* ---- Takeaway packs ---------------------------------------------
         Every one of these mutates the basket only. None of them touches a
         price: the summary is recomputed from the same lines by the same
         KT.rules call as before, and the server recomputes it again at
         checkout regardless of what the basket claims. */
      var addPack = e.target.closest("[data-takeaway-add]");
      if (addPack) {
        var made = KT.cart.addGroup();
        if (made == null) {
          KT.toast("That is as many packs as one order can have.", "info");
        } else {
          KT.toast("Takeaway " + made + " added.", "success");
        }
      }

      var pick = e.target.closest("[data-takeaway-pick]");
      if (pick) KT.cart.setActiveGroup(pick.getAttribute("data-takeaway-pick"));

      var drop = e.target.closest("[data-takeaway-drop]");
      if (drop) KT.cart.removeGroup(drop.getAttribute("data-takeaway-drop"));

      var move = e.target.closest("[data-takeaway-move]");
      if (move) {
        KT.cart.moveLine(move.getAttribute("data-takeaway-move"),
                         move.getAttribute("data-takeaway-to"));
      }
    });

    document.addEventListener("submit", function (e) {
      var form = e.target.closest("[data-promo-form]");
      if (!form) return;
      e.preventDefault();
      var input = KT.qs("input", form);
      var result = KT.cart.applyCoupon(KT.cart.summary().couponCode ? "" : input.value);
      var msg = KT.qs("[data-promo-msg]");
      if (msg) {
        msg.textContent = result.message;
        msg.style.color = result.ok ? "var(--mint)" : "var(--chili)";
      }
    });
  };
})(window.KT || (window.KT = {}));
